### ISSUE TITLE
Pendente jurisdictions cada departamento

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preserv-CO#12]
Para a carga de isolevel=3, tal como foi feito no Brasil, por ex. [AM/jurisdictionLevel8.csv](https://github.com/digital-guard/preserv-BR/blob/main/data/AM/jurisdictionLevel8.csv).

Requer geração e recuperação PostgreSQL automáticas por *makefile*, pois todos encontram-se distribuidos.

Requer makefile standalone para a gestão ser realizada pelos responsáveis locais.  Pendente mostrar também que DIVIPOLA, Wikidata e OSM são fontes com respectivos make_confs realizando a contribuição... Depois usar um algoritmo de validação cruzada e consolidação. Os INSERTs e UPDATEs da consolidação também precisam constar: qualquer pessoa com essas fontes deveria ser capaz de reproduzir o processo em comandos make. Documentar em WS como (metodologia) essa reconstrução pode ser feita.

**Comment by 0e1** [comment]
Cada departamento já possui seus arquivos de jurisdições.

As demandas restantes foram migradas para o Preserv: https://github.com/digital-guard/preserv/issues/93#issuecomment-1699583017
