### ISSUE TITLE
github não aceita arquivos grandes

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-CO#15]
carlos@addressforall:/var/gits/_dg/preservCutGeo-CO2021/data$ git push
Username for 'https://github.com': crebollo@gmail.com
Password for 'https://crebollo@gmail.com@github.com': 
Enumerating objects: 153, done.
Counting objects: 100% (153/153), done.
Delta compression using up to 4 threads
Compressing objects: 100% (148/148), done.
Writing objects: 100% (151/151), 35.59 MiB | 3.27 MiB/s, done.
Total 151 (delta 10), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (10/10), done.
remote: error: Trace: 3587b0f1966d7bf4a5d9f5fe64f8929542ce0c06f9e85d18211a16d9d023c3b5
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File data/_pk0006.01/datagrid/pts_d.geojson is 130.42 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
To https://github.com/digital-guard/preservCutGeo-CO2021.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/digital-guard/preservCutGeo-CO2021.git'

**Comment by 0e1** [comment]
Conforme https://github.com/digital-guard/preserv/issues/115#issuecomment-1295908278 grades não devem ser publicadas.

Então, não precisamos lidar com arquivos grandes no github nesse momento.
