### ISSUE TITLE
DC/Bogota/_pk001 nome alternativo

### ISSUE THREAD

**Issue by crebollobr** [digital-guard/preserv-CO#3]
Mesmo problema que #2 

Nome codificado MVINOMBRE
Nome de batismo MVINALTERN

Na busca por rua usar os dois nomes

Coalesce(MVINALTERN,MVINOMBRE) AS via_name

**Comment by ppKrauss** [comment]
Ver análise de perfil em https://github.com/digital-guard/preserv-CO/wiki/Medell%C3%ADn-e-Bogot%C3%A1
para entender melhor como compor a string de endereço (address) como _"via_name # housenumber"_ dentro das convenções da Colombia.
